### ISSUE TITLE
Standard UICollectionView drag and drop functionality does not work when LNTouchVisualizer is active

### ISSUE THREAD

**Issue by theextremeprogrammer** [LeoNatan/LNTouchVisualizer#1]
First, thank you for providing this library! I used to use the COSTouchVisualizer in previous projects. I found it helpful, and I’m glad to see this version ported over to Swift, making it easier to integrate into modern projects. Thanks!

I recently encountered some unexpected behavior in a specific use case.

**Scenario:** After beginning a drag and drop session inside a UICollectionView (`dragInteractionEnabled = true`) during the drag and drop process. 

**Without LNTouchVisualizer:**  
UICollectionView drag and drop functionality works as expected, calling all `UICollectionViewDragDelegate` and `UICollectionViewDropDelegate` methods.

**With LNTouchVisualizer:**  
UICollectionView drag and drop functionality does not work as expected. The `UICollectionViewDragDelegate` function `collectionView(_ collectionView: UICollectionView, itemsForBeginning session: UIDragSession, at indexPath: IndexPath)` is called as expected. 

However, `UICollectionViewDropDelegate` methods `collectionView(_ collectionView: UICollectionView, dropSessionDidUpdate session: UIDropSession, withDestinationIndexPath destinationIndexPath: IndexPath?)` and `collectionView(_ collectionView: UICollectionView, performDropWith coordinator: UICollectionViewDropCoordinator)` are never invoked. As a result, the "dropping" portion of the "drag and drop" implementation cannot be completed for the user. 

I have yet to have the time to put together a sample project to recreate this issue. If it would be helpful, I can try to create one.

Thanks for your support!

**Comment by LeoNatan** [comment]
Hello,

thank you for reporting this issue. 
I haven’t played with those drag drop APIs, so it would be very helpful if you can provide a small project, reproducing the issue. 

Thanks

**Comment by LeoNatan** [comment]
@theextremeprogrammer Ping. Are you able to provide a minimal project that reproduces the issue?
Thanks

**Comment by theextremeprogrammer** [comment]
Thanks for following up with me @LeoNatan!

I am busy with higher priority items for the next couple of weeks. I’d be happy to put together a sample project but it won’t be until the first week of August likely. If that works for you I will follow up with you around that time. 👍🏻 Thanks!

**Comment by LeoNatan** [comment]
Hello
Sure, we’ll keep the issue open. 
Thanks

**Comment by theextremeprogrammer** [comment]
Thanks for your patience, @LeoNatan! 🙏

Please find the reproducer here: https://github.com/theextremeprogrammer/LNTouchVisualizer-Repro

And a couple of screen captures showing the behavior:
- https://www.dropbox.com/scl/fi/nwyphvqi9uf7t2n46u4ij/LNTouchVisualizer-Repro-First-Drop-Works-Then-Broken.mp4?rlkey=g5rajunveghcwbng80kybsjsf&dl=0
- https://www.dropbox.com/scl/fi/sqs0yxigvxqqvwo7wg6mc/LNTouchVisualizer-Repro-First-Drop-Not-Working-Sometimes.mp4?rlkey=g9ejnlxqxtr0ln6xoxamat564&dl=0

Please let me know how else I can help. Thanks for your support! 🙇🏻‍♂️

**Comment by LeoNatan** [comment]
Thanks. Please keep the repo alive. I will take a look soon.

**Comment by LeoNatan** [comment]
Do you know why the first drop works but fails later? Is this only with the framework enabled? Thanks

**Comment by theextremeprogrammer** [comment]
Yes, it’s only when the framework enabled. You can easily verify by disabling the framework in the same project and retesting. 

I don’t know why the first drop works but subsequent ones fail later. That’s the core issue I believe. I added some logging to the methods in my project to try and understand what was happening and it wasn’t clear to me what was causing the issue.

**Comment by LeoNatan** [comment]
Fixed.

Please try with 1.0.4.

**Comment by theextremeprogrammer** [comment]
Hi @LeoNatan! I just pulled the latest version and tested and everything is working great. Thank you so much for taking the time to research and resolve this issue. I really appreciate it! 🙏 All the best, Derek

**Comment by LeoNatan** [comment]
Happy coding!
